# fly.toml app configuration file generated for ilungi-gestora-api on 2026-02-05T11:19:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ilungi-gestora-api'
primary_region = 'jnb'

[build]
  dockerfile = 'Dockerfile'

[env]
  JAVA_OPTS = '-Xmx256m -Xms64m -Dserver.address=0.0.0.0'
  PORT = '8080'
  SPRING_PROFILES_ACTIVE = 'prod'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/actuator/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
